currency_analyzer/main/routes.py
import re
from flask import (
    render_template,
    Blueprint,
    request,
    url_for,
    make_response,
    flash,
    redirect,
    session,
)
from sqlalchemy import func
from datetime import datetime, timedelta, date
from currency_analyzer import db, cache
from currency_analyzer.main.models import Currency, ExchangeRates, ExchangeRatesPredictions
from currency_analyzer.main.utils import (
    add_notification_refresh_header,
    add_page_refresh_header,
    FLASH_MESSAGE_AVAILABLE_SESSION_VAR,
    REFRESH_PAGE_SESSION_VAR,
)
from currency_analyzer.main.currency_value import CurrencyValues
from currency_analyzer.main.currency_stats import CurrencyStats, get_currency_stats
from currency_analyzer.main.currency_prediction import get_latest_predictions_for_currencies, get_latest_predictions_dict

main = Blueprint("main", __name__)
WATCHED_CURRENCY_SESSION_VAR = "watched_currencies"
TIMESTAMPS_FOR_ANALYZE_SESSION_VAR = "timestamp_for_analyze"
UPDATING_ANALYZE_ZOOM_SESSION_VAR = "updating_analyze_zoom"
ANALYZE_ZOOM_DAYS_SESSION_VAR = "analyze_zoom_days"
MIN_ZOOM_VALUE = 1
WATCHED_CURRENCY_LIMIT = 6
DATETIME_FORMAT = "%Y-%m-%d"


@main.route("/heartbeat")
def heartbeat():
    return ""

@main.route("/dev/clear")
def clear():
    session[TIMESTAMPS_FOR_ANALYZE_SESSION_VAR] = None
    session[ANALYZE_ZOOM_DAYS_SESSION_VAR] = 1
    session[UPDATING_ANALYZE_ZOOM_SESSION_VAR] = False
    return "OK"

@main.route("/notifications")
def notifications():
    return render_template("partials/notifications.html")


@main.route("/")
@add_notification_refresh_header
def index():
    return render_template('index.html', htmx_link_to_load=url_for('main.analyze'))


def normalize_date_based_on_zoom(date_to_normalize: date, zoom: int) -> date:
    if zoom == 7:
        while (date_to_normalize.weekday() != 0):
            date_to_normalize -= timedelta(days=1)
        return date_to_normalize
    elif zoom == 30:
        return date_to_normalize.replace(day=1)
    elif zoom == 365:
        return date_to_normalize.replace(month=1, day=1)
    return date_to_normalize


def get_labels_and_datetimes_in_timeframe(
    timestamp_since: date, timestamp_to: date, timedelta_days: int = 1
):
    labels = []
    datetimes = []
    
    x = normalize_date_based_on_zoom(timestamp_to, timedelta_days)
    target_timestamp = normalize_date_based_on_zoom(timestamp_since, timedelta_days)
    while x >= target_timestamp:
        x = normalize_date_based_on_zoom(x, timedelta_days)
        labels.append(date.strftime(x, DATETIME_FORMAT))
        datetimes.append(x)
        x -= timedelta(days=1)
    return labels, datetimes


def get_timestamps(request, earliest_timestamp) -> (date, date):
    datetime_pattern = re.compile('^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
    timestamp_since = request.args.get("since", default=None)
    if timestamp_since is None:
        timestamp_since = date.today() - timedelta(days=30)
    elif not datetime_pattern.match(timestamp_since):
        timestamp_since = date.today() - timedelta(days=30)
        flash(f"Could not parse since date. Using default '{timestamp_since.strftime(DATETIME_FORMAT)}'.", "error")
        session[FLASH_MESSAGE_AVAILABLE_SESSION_VAR] = True
    else:
        timestamp_since = date.fromisoformat(timestamp_since)

    timestamp_to = request.args.get("to", default=None)
    if timestamp_to is None:
        timestamp_to = date.today() - timedelta(days=1)
    elif not datetime_pattern.match(timestamp_to):
        timestamp_to = date.today() - timedelta(days=1)
        flash(f"Could not parse to date. Using default '{timestamp_to.strftime(DATETIME_FORMAT)}'.", "error")
        session[FLASH_MESSAGE_AVAILABLE_SESSION_VAR] = True

    else:
        timestamp_to = date.fromisoformat(timestamp_to)

    if timestamp_since < earliest_timestamp:
        timestamp_since = earliest_timestamp

    if timestamp_to < timestamp_since:
        return (
            date.today() - timedelta(days=30),
            date.today() - timedelta(days=1)
        )

    return timestamp_since, timestamp_to


def agregate_values_to_zoom(currency_code: str, label_datetime: datetime, zoom: int) -> list[dict]:
    earlier_timestamp = normalize_date_based_on_zoom(label_datetime - timedelta(days=1), zoom)
    result = (db.session.query(func.avg(ExchangeRates.rate))
            .filter(ExchangeRates.code == currency_code)
            .filter(ExchangeRates.date.between(earlier_timestamp, label_datetime)).first()
    )[0]
    if result is None:
        return 'NO DATA'
    return float(result)


def get_currency_values_for_datetimes(currencies: list[Currency], datetimes: list[datetime], zoom: int) -> list[dict]:
    currency_values = []
    for currency in currencies:
        values = []
        if zoom > 1:
            for datetime in datetimes:
                values.append(agregate_values_to_zoom(currency.code, datetime, zoom))
            currency_values.append({"name": currency.code, "values": values})
        else:
            for datetime in datetimes:
                values.append(ExchangeRates.query.filter(ExchangeRates.code == currency.code).filter(ExchangeRates.date == datetime).one_or_none())
            currency_values.append(CurrencyValues(currency.code, values).serialize())
    return currency_values


def get_high_low_average_change_data_between_timestamps(currencies: list[Currency], from_date: datetime, to_date: datetime) -> list[dict]:
    currency_stats = []
    for currency in currencies:
        earliest_timestamp_for_currency = (ExchangeRates.query
            .filter(ExchangeRates.code == currency.code)
            .order_by(ExchangeRates.date)
            .first()
        ).date
        currency_stats.append(
            {
                "30days": CurrencyStats().init_from_currency(currency, date.today() - timedelta(days=30), date.today()).serialize(),
                "90days": CurrencyStats().init_from_currency(currency, date.today() - timedelta(days=90), date.today()).serialize(),
                "all": CurrencyStats().init_from_currency(currency, earliest_timestamp_for_currency, date.today()).serialize(),
                "selected": CurrencyStats().init_from_currency(currency, from_date, to_date).serialize(),
            }
        )
    return currency_stats


def is_zoom_being_updated() -> bool:
    return UPDATING_ANALYZE_ZOOM_SESSION_VAR in session and session[UPDATING_ANALYZE_ZOOM_SESSION_VAR]


@main.route("/analyze")
@add_notification_refresh_header
def analyze():
    if not WATCHED_CURRENCY_SESSION_VAR in session:
        session[WATCHED_CURRENCY_SESSION_VAR] = []
    currencies = Currency.query.filter(
        Currency.id.in_(session[WATCHED_CURRENCY_SESSION_VAR])
    ).order_by(Currency.code).all()

    if not ANALYZE_ZOOM_DAYS_SESSION_VAR in session:
        session[ANALYZE_ZOOM_DAYS_SESSION_VAR] = 1
    zoom = session[ANALYZE_ZOOM_DAYS_SESSION_VAR]

    if is_zoom_being_updated():
        timestamp_since, timestamp_to = (
            datetime.strptime(session[TIMESTAMPS_FOR_ANALYZE_SESSION_VAR][0], DATETIME_FORMAT),
            datetime.strptime(session[TIMESTAMPS_FOR_ANALYZE_SESSION_VAR][1], DATETIME_FORMAT),
        )
        session[UPDATING_ANALYZE_ZOOM_SESSION_VAR] = False
    else:
        earliest_timestamp = (ExchangeRates.query
            .order_by(ExchangeRates.date)
            .first()
        ).date
        timestamp_since, timestamp_to = get_timestamps(request, earliest_timestamp)
        session[TIMESTAMPS_FOR_ANALYZE_SESSION_VAR] = (
            timestamp_since.strftime(DATETIME_FORMAT), 
            timestamp_to.strftime(DATETIME_FORMAT)
        )
    labels, datetimes = get_labels_and_datetimes_in_timeframe(timestamp_since, timestamp_to, zoom)
    currency_values = get_currency_values_for_datetimes(currencies, datetimes, zoom)
    currency_stats = get_high_low_average_change_data_between_timestamps(currencies, timestamp_since, timestamp_to)
    latest_predictions = get_latest_predictions_for_currencies(currencies)
    return render_template(
        "currency_analyze.html",
        labels=labels,
        currency_values=currency_values,
        currency_stats=currency_stats,
        since=timestamp_since.strftime(DATETIME_FORMAT),
        to=timestamp_to.strftime(DATETIME_FORMAT),
        zoom=zoom,
        watched_currencies_count=len(session[WATCHED_CURRENCY_SESSION_VAR]),
        latest_predictions=latest_predictions
    )


@main.route("/analyze/zoom/<int:zoom>")
def analyze_zoom(zoom: int):
    session[UPDATING_ANALYZE_ZOOM_SESSION_VAR] = True
    if zoom < MIN_ZOOM_VALUE:
        zoom = MIN_ZOOM_VALUE
    session[ANALYZE_ZOOM_DAYS_SESSION_VAR] = zoom
    return redirect(url_for('main.analyze'))


@main.route("/list")
@cache.cached(timeout=3600)
def currency_list():
    if not WATCHED_CURRENCY_SESSION_VAR in session:
        session[WATCHED_CURRENCY_SESSION_VAR] = []
    watched_currencies = [
        c for c in Currency.query.filter(
            Currency.id.in_(session[WATCHED_CURRENCY_SESSION_VAR])
        ).order_by(Currency.code).all()
    ]
    serialized_watched_currencies = [c.serialize for c in watched_currencies]
    currencies, currency_stats_dict = get_currency_stats()
    currency_predictions_dict = get_latest_predictions_dict(currencies)
    
    return render_template(
        "currency_list.html",
        currencies=currencies,
        currency_stats_dict=currency_stats_dict,
        watched_currencies=serialized_watched_currencies,
        watched_currencies_ids=session[WATCHED_CURRENCY_SESSION_VAR],
        currency_predictions_dict=currency_predictions_dict,
        latest_prediction_date=next(iter(currency_predictions_dict.values())).date
    )


@main.route("/currency/watched/list")
@add_notification_refresh_header
@add_page_refresh_header
def currency_watch_list():
    if not WATCHED_CURRENCY_SESSION_VAR in session:
        return render_template("partials/watch_list.html", watched_currencies=[])

    serialized_watched_currencies = [

currency_analyzer/templates/partials/currency_list_row.html
{% if currency.id in watched_currencies_ids %}
    <tr class="active" id="{{ currency.code }}" hx-trigger="click" hx-target="this">
        <td><div hx-get="{{ url_for('main.currency_unwatch', currency_id=currency.id) }}" hx-target="#watch-list" hx-trigger="click from:closest tr"><img src="{{ url_for('static', filename=currency.image_path) }}"></div></td>
        <td>{{ currency.code }}</td>
        <td>{{ currency_stats.high }}</td>
        <td>{{ currency_stats.low }}</td>
        <td>{{ currency_stats.avg }}</td>
        <td>{{ currency_stats.change }}</td>
        <td>{{ currency_stats.change_perc }}</td>
        <td>{{ currency_prediction.prediction }}</td>
        <td><div class="remove" hx-get="{{ url_for('main.currency_watch_list_row', currency_id=currency.id) }}" hx-target="closest tr" hx-swap="outerHTML" hx-trigger="click from:closest tr queue:last delay:.1s">-</div></td>
    </tr>
{% else %}
    <tr id="{{ currency.code }}" hx-trigger="click" hx-target="this">
        <td><div hx-get="{{ url_for('main.currency_watch', currency_id=currency.id) }}" hx-target="#watch-list" hx-trigger="click from:closest tr"><img src="{{ url_for('static', filename=currency.image_path) }}"></div></td>
        <td>{{ currency.code }}</td>
        <td>{{ currency_stats.high }}</td>
        <td>{{ currency_stats.low }}</td>
        <td>{{ currency_stats.avg }}</td>
        <td>{{ currency_stats.change }}</td>
        <td>{{ currency_stats.change_perc }}</td>
        <td>{{ currency_prediction.prediction }}</td>
        <td><div class="add" hx-get="{{ url_for('main.currency_watch_list_row', currency_id=currency.id) }}" hx-target="closest tr" hx-swap="outerHTML" hx-trigger="click from:closest tr queue:last delay:.1s">+</div></td>
    </tr>
{% endif %}
<script>
    tableRecords = document.querySelectorAll("td:nth-child(2)");
    numberRecords = document.querySelectorAll("tr#{{ currency.code }} td:nth-child(3), tr#{{ currency.code }} td:nth-child(4), tr#{{ currency.code }} td:nth-child(5), tr#{{ currency.code }} td:nth-child(6)");
    percentageRecords = document.querySelectorAll("tr#{{ currency.code }} td:nth-child(7), tr#{{ currency.code }} td:nth-child(8)");
</script>
{% if currency_stats.found_data_in_range == 'true' %}
<script>
    numberRecords.forEach(td => {
        td.innerText = parseFloat(td.innerText).toFixed(3);
        td.innerText = td.innerText + ' PLN';
    });
    percentageRecords.forEach(td => {
        td.innerText = parseFloat(td.innerText).toFixed(3);
        td.innerText = td.innerText + ' %';
    });
</script>
{% else %}
<script>
    numberRecords.forEach(td => {
        td.innerText = '-';
    });
    percentageRecords.forEach(td => {
        td.innerText = '-';
    });
</script>
{% endif %}

currency_analyzer/templates/partials/notifications.html
<div class="notifications" hx-get="{{ url_for('main.notifications') }}" hx-trigger="newNotification from:window">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="notification {{ category }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
    <script>hideOnClick(".notifications .notification");</script>
</div>

currency_analyzer/templates/partials/watch_list.html
<div class="picked-currencies" id="watch-list">
    <h4>{{ watched_currencies|length }}/6</h4>
    {% for currency in watched_currencies %}
        <div class="currency" hx-get="{{ url_for('main.currency_unwatch_refresh', currency_id=currency.id) }}" hx-target="#watch-list">
            <img src="{{ url_for('static', filename=currency.image_path) }}">
            <p>{{ currency.code }}</p>
            <div class="remove">-</div>
        </div>
    {% endfor %}
    {% if watched_currencies|length %}
        <div>
            <h4 hx-get="{{ url_for('main.currency_watch_list_clear') }}" hx-target="#watch-list">Clear</h4>
        </div>
    {% endif %}
</div>