currency_analyzer/main/routes.py
import re
from flask import (
    render_template,
    Blueprint,
    request,
    url_for,
    make_response,
    flash,
    redirect,
    session,
)
from sqlalchemy import func
from datetime import datetime, timedelta, date
from currency_analyzer import db, cache
from currency_analyzer.main.models import Currency, ExchangeRates, ExchangeRatesPredictions
from currency_analyzer.main.utils import (
    add_notification_refresh_header,
    add_page_refresh_header,
    FLASH_MESSAGE_AVAILABLE_SESSION_VAR,
    REFRESH_PAGE_SESSION_VAR,
)
from currency_analyzer.main.currency_value import CurrencyValues
from currency_analyzer.main.currency_stats import CurrencyStats, get_currency_stats
from currency_analyzer.main.currency_prediction import get_latest_predictions_for_currencies, get_latest_predictions_dict

main = Blueprint("main", __name__)
WATCHED_CURRENCY_SESSION_VAR = "watched_currencies"
TIMESTAMPS_FOR_ANALYZE_SESSION_VAR = "timestamp_for_analyze"
UPDATING_ANALYZE_ZOOM_SESSION_VAR = "updating_analyze_zoom"
ANALYZE_ZOOM_DAYS_SESSION_VAR = "analyze_zoom_days"
MIN_ZOOM_VALUE = 1
WATCHED_CURRENCY_LIMIT = 6
DATETIME_FORMAT = "%Y-%m-%d"


@main.route("/heartbeat")
def heartbeat():
    return ""

@main.route("/dev/clear")
def clear():
    session[TIMESTAMPS_FOR_ANALYZE_SESSION_VAR] = None
    session[ANALYZE_ZOOM_DAYS_SESSION_VAR] = 1
    session[UPDATING_ANALYZE_ZOOM_SESSION_VAR] = False
    return "OK"

@main.route("/notifications")
def notifications():
    return render_template("partials/notifications.html")


@main.route("/")
@add_notification_refresh_header
def index():
    return render_template('index.html', htmx_link_to_load=url_for('main.analyze'))


def normalize_date_based_on_zoom(date_to_normalize: date, zoom: int) -> date:
    if zoom == 7:
        while (date_to_normalize.weekday() != 0):
            date_to_normalize -= timedelta(days=1)
        return date_to_normalize
    elif zoom == 30:
        return date_to_normalize.replace(day=1)
    elif zoom == 365:
        return date_to_normalize.replace(month=1, day=1)
    return date_to_normalize


def get_labels_and_datetimes_in_timeframe(
    timestamp_since: date, timestamp_to: date, timedelta_days: int = 1
):
    labels = []
    datetimes = []
    
    x = normalize_date_based_on_zoom(timestamp_to, timedelta_days)
    target_timestamp = normalize_date_based_on_zoom(timestamp_since, timedelta_days)
    while x >= target_timestamp:
        x = normalize_date_based_on_zoom(x, timedelta_days)
        labels.append(date.strftime(x, DATETIME_FORMAT))
        datetimes.append(x)
        x -= timedelta(days=1)
    return labels, datetimes


def get_timestamps(request, earliest_timestamp) -> (date, date):
    datetime_pattern = re.compile('^[0-9]{4}-[0-9]{2}-[0-9]{2}$')
    timestamp_since = request.args.get("since", default=None)
    if timestamp_since is None:
        timestamp_since = date.today() - timedelta(days=30)
    elif not datetime_pattern.match(timestamp_since):
        timestamp_since = date.today() - timedelta(days=30)
        flash(f"Could not parse since date. Using default '{timestamp_since.strftime(DATETIME_FORMAT)}'.", "error")
        session[FLASH_MESSAGE_AVAILABLE_SESSION_VAR] = True
    else:
        timestamp_since = date.fromisoformat(timestamp_since)

    timestamp_to = request.args.get("to", default=None)
    if timestamp_to is None:
        timestamp_to = date.today() - timedelta(days=1)
    elif not datetime_pattern.match(timestamp_to):
        timestamp_to = date.today() - timedelta(days=1)
        flash(f"Could not parse to date. Using default '{timestamp_to.strftime(DATETIME_FORMAT)}'.", "error")
        session[FLASH_MESSAGE_AVAILABLE_SESSION_VAR] = True

    else:
        timestamp_to = date.fromisoformat(timestamp_to)

    if timestamp_since < earliest_timestamp:
        timestamp_since = earliest_timestamp

    if timestamp_to < timestamp_since:
        return (
            date.today() - timedelta(days=30),
            date.today() - timedelta(days=1)
        )

    return timestamp_since, timestamp_to


def agregate_values_to_zoom(currency_code: str, label_datetime: datetime, zoom: int) -> list[dict]:
    earlier_timestamp = normalize_date_based_on_zoom(label_datetime - timedelta(days=1), zoom)
    result = (db.session.query(func.avg(ExchangeRates.rate))
            .filter(ExchangeRates.code == currency_code)
            .filter(ExchangeRates.date.between(earlier_timestamp, label_datetime)).first()
    )[0]
    if result is None:
        return 'NO DATA'
    return float(result)


def get_currency_values_for_datetimes(currencies: list[Currency], datetimes: list[datetime], zoom: int) -> list[dict]:
    currency_values = []
    for currency in currencies:
        values = []
        if zoom > 1:
            for datetime in datetimes:
                values.append(agregate_values_to_zoom(currency.code, datetime, zoom))
            currency_values.append({"name": currency.code, "values": values})
        else:
            for datetime in datetimes:
                values.append(ExchangeRates.query.filter(ExchangeRates.code == currency.code).filter(ExchangeRates.date == datetime).one_or_none())
            currency_values.append(CurrencyValues(currency.code, values).serialize())
    return currency_values


def get_high_low_average_change_data_between_timestamps(currencies: list[Currency], from_date: datetime, to_date: datetime) -> list[dict]:
    currency_stats = []
    for currency in currencies:
        earliest_timestamp_for_currency = (ExchangeRates.query
            .filter(ExchangeRates.code == currency.code)
            .order_by(ExchangeRates.date)
            .first()
        ).date
        currency_stats.append(
            {
                "30days": CurrencyStats().init_from_currency(currency, date.today() - timedelta(days=30), date.today()).serialize(),
                "90days": CurrencyStats().init_from_currency(currency, date.today() - timedelta(days=90), date.today()).serialize(),
                "all": CurrencyStats().init_from_currency(currency, earliest_timestamp_for_currency, date.today()).serialize(),
                "selected": CurrencyStats().init_from_currency(currency, from_date, to_date).serialize(),
            }
        )
    return currency_stats


def is_zoom_being_updated() -> bool:
    return UPDATING_ANALYZE_ZOOM_SESSION_VAR in session and session[UPDATING_ANALYZE_ZOOM_SESSION_VAR]


@main.route("/analyze")
@add_notification_refresh_header
def analyze():
    if not WATCHED_CURRENCY_SESSION_VAR in session:
        session[WATCHED_CURRENCY_SESSION_VAR] = []
    currencies = Currency.query.filter(
        Currency.id.in_(session[WATCHED_CURRENCY_SESSION_VAR])
    ).order_by(Currency.code).all()

    if not ANALYZE_ZOOM_DAYS_SESSION_VAR in session:
        session[ANALYZE_ZOOM_DAYS_SESSION_VAR] = 1
    zoom = session[ANALYZE_ZOOM_DAYS_SESSION_VAR]

    if is_zoom_being_updated():
        timestamp_since, timestamp_to = (
            datetime.strptime(session[TIMESTAMPS_FOR_ANALYZE_SESSION_VAR][0], DATETIME_FORMAT),
            datetime.strptime(session[TIMESTAMPS_FOR_ANALYZE_SESSION_VAR][1], DATETIME_FORMAT),
        )
        session[UPDATING_ANALYZE_ZOOM_SESSION_VAR] = False
    else:
        earliest_timestamp = (ExchangeRates.query
            .order_by(ExchangeRates.date)
            .first()
        ).date
        timestamp_since, timestamp_to = get_timestamps(request, earliest_timestamp)
        session[TIMESTAMPS_FOR_ANALYZE_SESSION_VAR] = (
            timestamp_since.strftime(DATETIME_FORMAT), 
            timestamp_to.strftime(DATETIME_FORMAT)
        )
    labels, datetimes = get_labels_and_datetimes_in_timeframe(timestamp_since, timestamp_to, zoom)
    currency_values = get_currency_values_for_datetimes(currencies, datetimes, zoom)
    currency_stats = get_high_low_average_change_data_between_timestamps(currencies, timestamp_since, timestamp_to)
    latest_predictions = get_latest_predictions_for_currencies(currencies)
    return render_template(
        "currency_analyze.html",
        labels=labels,
        currency_values=currency_values,
        currency_stats=currency_stats,
        since=timestamp_since.strftime(DATETIME_FORMAT),
        to=timestamp_to.strftime(DATETIME_FORMAT),
        zoom=zoom,
        watched_currencies_count=len(session[WATCHED_CURRENCY_SESSION_VAR]),
        latest_predictions=latest_predictions
    )


@main.route("/analyze/zoom/<int:zoom>")
def analyze_zoom(zoom: int):
    session[UPDATING_ANALYZE_ZOOM_SESSION_VAR] = True
    if zoom < MIN_ZOOM_VALUE:
        zoom = MIN_ZOOM_VALUE
    session[ANALYZE_ZOOM_DAYS_SESSION_VAR] = zoom
    return redirect(url_for('main.analyze'))


@main.route("/list")
@cache.cached(timeout=3600)
def currency_list():
    if not WATCHED_CURRENCY_SESSION_VAR in session:
        session[WATCHED_CURRENCY_SESSION_VAR] = []
    watched_currencies = [
        c for c in Currency.query.filter(
            Currency.id.in_(session[WATCHED_CURRENCY_SESSION_VAR])
        ).order_by(Currency.code).all()
    ]
    serialized_watched_currencies = [c.serialize for c in watched_currencies]
    currencies, currency_stats_dict = get_currency_stats()
    currency_predictions_dict = get_latest_predictions_dict(currencies)
    
    return render_template(
        "currency_list.html",
        currencies=currencies,
        currency_stats_dict=currency_stats_dict,
        watched_currencies=serialized_watched_currencies,
        watched_currencies_ids=session[WATCHED_CURRENCY_SESSION_VAR],
        currency_predictions_dict=currency_predictions_dict,
        latest_prediction_date=next(iter(currency_predictions_dict.values())).date
    )


@main.route("/currency/watched/list")
@add_notification_refresh_header
@add_page_refresh_header
def currency_watch_list():
    if not WATCHED_CURRENCY_SESSION_VAR in session:
        return render_template("partials/watch_list.html", watched_currencies=[])

    serialized_watched_currencies = [

currency_analyzer/templates/currency_analyze.html
<div class="info">
    <h2>Analyzer</h2>
    <div class="filters">
        <div class="timeview-filter-list">
            <a href="#" class="{{ 'active' if zoom == 1 }}" hx-get="{{ url_for('main.analyze_zoom', zoom=1) }}" hx-target="#wrapper" hx-indicator="#loading-overlay">D</a>
            <a href="#" class="{{ 'active' if zoom == 7 }}" hx-get="{{ url_for('main.analyze_zoom', zoom=7) }}" hx-target="#wrapper" hx-indicator="#loading-overlay">W</a>
            <a href="#" class="{{ 'active' if zoom == 30 }}" hx-get="{{ url_for('main.analyze_zoom', zoom=30) }}" hx-target="#wrapper" hx-indicator="#loading-overlay">M</a>
            <a href="#" class="{{ 'active' if zoom == 365 }}" hx-get="{{ url_for('main.analyze_zoom', zoom=365) }}" hx-target="#wrapper" hx-indicator="#loading-overlay">Y</a>
        </div>
        <hr/>
        <div class="filter-list" id="filter-list">
            <a href="#" hx-get="{{ url_for('main.analyze') }}" hx-target="#wrapper" hx-indicator="#loading-overlay">7d</a>
            <a href="#" hx-get="{{ url_for('main.analyze') }}" hx-target="#wrapper" hx-indicator="#loading-overlay">1m</a>
            <a href="#" hx-get="{{ url_for('main.analyze') }}" hx-target="#wrapper" hx-indicator="#loading-overlay">3m</a>
            <a href="#" hx-get="{{ url_for('main.analyze') }}" hx-target="#wrapper" hx-indicator="#loading-overlay">6m</a>
            <a href="#" hx-get="{{ url_for('main.analyze') }}" hx-target="#wrapper" hx-indicator="#loading-overlay">1y</a>
        </div>
        <form class="search-timeframe">
            <label for="sinceDatetime">Since:</label>
            <input type="datetime" name="since" id="sinceDatetime" value="{{ since }}">
            <label for="toDatetime">To:</label>
            <input type="datetime" name="to" id="toDatetime" value="{{ to }}">
            <button class="btn" hx-get="{{ url_for('main.analyze') }}" hx-target="#wrapper" hx-vals="js:{since: getInputVal('sinceDatetime'), to: getInputVal('toDatetime')}" hx-indicator="#loading-overlay">Filter</button>
        </form>
    </div>
</div>
{% if watched_currencies_count == 0 %}
    <div class="main-graph">
        <h2>No currencies selected</h2>
    </div>
{% else %}
    <div class="main-graph">
        <div>
            <h2></h2>
            <hr/>
            <canvas id="mainChart" width="1200" height="400"></canvas>
        </div>
    </div>
    <div class="graphs">
        {% for currency in currency_values %}
            <div>
                <h2>{{ currency['name'] }} Value</h2>
                <hr/>
                <canvas class="normal-chart" width="600" height="300"></canvas>
            </div>
        {% endfor %}
    </div>
    <div class="tables">
        <div class="table">
            <h2>Last 30 Days</h2>
            <table>
                <tr>
                    <th sort-key="currency">Currency<i class='bx bx-sort'></i></th>
                    <th sort-key="high">High<i class='bx bx-sort'></i></th>
                    <th sort-key="low">Low<i class='bx bx-sort'></i></th>
                    <th sort-key="avg">Average<i class='bx bx-sort'></i></th>
                    <th sort-key="change">Change<i class='bx bx-sort'></i></th>
                    <th sort-key="change_perc">Change (%)<i class='bx bx-sort'></i></th>
                </tr>
            </table>
        </div>
        <div class="table">
            <h2>Last 90 Days</h2>
            <table>
                <tr>
                    <th sort-key="currency">Currency<i class='bx bx-sort'></i></th>
                    <th sort-key="high">High<i class='bx bx-sort'></i></th>
                    <th sort-key="low">Low<i class='bx bx-sort'></i></th>
                    <th sort-key="avg">Average<i class='bx bx-sort'></i></th>
                    <th sort-key="change">Change<i class='bx bx-sort'></i></th>
                    <th sort-key="change_perc">Change (%)<i class='bx bx-sort'></i></th>
                </tr>
            </table>
        </div>
        <div class="table">
            <h2>All</h2>
            <table>
                <tr>
                    <th sort-key="currency">Currency<i class='bx bx-sort'></i></th>
                    <th sort-key="high">High<i class='bx bx-sort'></i></th>
                    <th sort-key="low">Low<i class='bx bx-sort'></i></th>
                    <th sort-key="avg">Average<i class='bx bx-sort'></i></th>
                    <th sort-key="change">Change<i class='bx bx-sort'></i></th>
                    <th sort-key="change_perc">Change (%)<i class='bx bx-sort'></i></th>
                </tr>
            </table>
        </div>
        <div class="table">
            <h2>From {{ since }} to {{ to }}</h2>
            <table>
                <tr>
                    <th sort-key="currency">Currency<i class='bx bx-sort'></i></th>
                    <th sort-key="high">High<i class='bx bx-sort'></i></th>
                    <th sort-key="low">Low<i class='bx bx-sort'></i></th>
                    <th sort-key="avg">Average<i class='bx bx-sort'></i></th>
                    <th sort-key="change">Change<i class='bx bx-sort'></i></th>
                    <th sort-key="change_perc">Change (%)<i class='bx bx-sort'></i></th>
                </tr>
            </table>
        </div>
        <div class="table">
            <h2>Prediction</h2>
            <table>
                <tr>
                    <th>Currency</th>
                    <th>Prediction date</th>
                    <th>Predicted change</th>
                </tr>
                {% for prediction in latest_predictions %}
                    <tr>
                        <td>{{ prediction.code }}</td>
                        <td>{{ prediction.date }}</td>
                        <td>{{ prediction.prediction }} %</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    </div>
    <script>
        var labels = {{ labels | safe }};
        var currencyValues = {{ currency_values | safe }};
        var currencyStats = {{ currency_stats | safe }};
    </script>
    <script src="{{ url_for('static', filename='js/charts.js') }}"></script>
    <script src="{{ url_for('static', filename='js/tables.js') }}"></script>
{% endif %}
<script>updateNavFocus('analyzer');</script>

currency_analyzer/templates/currency_list.html
{% extends "layout.html" %}
{% block content %}
    <div class="info">
        <h2>Currencies <i class='bx bx-info-circle' title="Currency stats seen in the table are from last 30 days"></i></h2>
        <div class="search-bar">
            <input type="text" name="currency-search" id="currency-search" placeholder="Search currency">
        </div>
    </div>
    <div class="main-graph">
        <h2>Latest prediction: {{ latest_prediction_date }}</h2>
    </div>
    <div class="currencies">
        <table>
            <tr>
                <th></th>
                <th>Currency</th>
                <th>High</th>
                <th>Low</th>
                <th>Average</th>
                <th>Change</th>
                <th>Change (%)</th>
                <th>Prediction</th>
                <th></th>
            </tr>
            {% for currency in currencies %}
                {% with currency_stats=currency_stats_dict[currency.code] %}
                    {% with currency_prediction=currency_predictions_dict[currency.code] %}
                        {% include 'partials/currency_list_row.html' %}
                    {% endwith %}
                {% endwith %}
            {% endfor %}
        </table>
    <script>updateNavFocus('currencies');</script>
    <script>
        colorChangeColumns(document.querySelectorAll(".currencies table"), 'td:nth-child(6), td:nth-child(7), td:nth-child(8)');
        document.querySelector(".currencies table").addEventListener('htmx:afterSwap', ()=> {colorChangeColumns(document.querySelectorAll(".currencies table"), 'td:nth-child(6), td:nth-child(7), td:nth-child(8)')});
    </script>
    <script src="{{ url_for('static', filename='js/search.js') }}"></script>
{% endblock content %}

currency_analyzer/templates/index.html
{% extends "layout.html" %}
{% block content %}
    <div class="loading-overlay htmx-indicator" hx-get="{{ htmx_link_to_load }}" hx-target="#wrapper" hx-trigger="load">
        <div class="loading">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
        </div>
    </div>
{% endblock content %}

currency_analyzer/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Analyzer | Currency Analyzer</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/favicon-green.ico') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <script src="https://unpkg.com/htmx.org@1.9.12" integrity="sha384-ujb1lZYygJmzgSwoxRggbCHcjc0rB2XoQrxeTUQyRjrOnlCoYta87iKBWq3EsdM2" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.4.1/dist/chart.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-crosshair@1.2.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-annotation@1.4.0/dist/chartjs-plugin-annotation.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chartjs-adapter-date-fns/dist/chartjs-adapter-date-fns.bundle.min.js"></script>
    <script src="{{ url_for('static', filename='js/app.js') }}"></script>
</head>
<body>
    <nav hx-get="{{ url_for('main.currency_watch_list') }}" hx-trigger="load" hx-target="#watch-list">
        <div class="logo">
            <img src="{{ url_for('static', filename='img/logo.png') }}" alt="Currency Analyzer">
        </div>
        <div class="menu">
            <a href="{{ url_for('main.currency_list') }}"><i class='bx bx-coin'></i>Currencies</a>
            <a href="{{ url_for('main.index') }}"><i class='bx bx-search'></i>Analyzer</a>
        </div>
        {% include 'partials/watch_list.html' %}
    </nav>
    {% include 'partials/notifications.html' %}
    <div class="wrapper" id="wrapper">
        {% block content %}{% endblock %}
    </div>
    <div id="loading-overlay" class="loading-overlay htmx-indicator">
        <div class="loading">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
        </div>
    </div>
</body>
</html>